apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-deploy-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: create-deploy-cr
subjects:
- kind: ServiceAccount
  name: cluster-deployer
  namespace: kube-system
