apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: configmap-pod
  name: configmap-pod
spec:
  containers:
  - image: nginx
    name: configmap-pod
    env: 
    - name: AIRLINE_KIOSK_1
      valueFrom:
        configMapKeyRef:
          name: airline-kiosks
          key: KIOSK_1
    - name: AIRLINE_KIOSK_2
      valueFrom:
        configMapKeyRef:
          name: airline-kiosks
          key: KIOSK_2
    - name: AIRLINE_KIOSK_3
      valueFrom:
        configMapKeyRef:
          name: airline-kiosks
          key: KIOSK_3
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
