apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mars-pv-rb
  namespace: mars
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-viewer
subjects:
- kind: ServiceAccount
  name: mars-viewer
  namespace: mars
