apiVersion: v1
kind: Pod
metadata:
  labels:
    run: secret-pod
  name: secret-pod
spec:
  containers:
  - image: nginx
    name: secret-pod
    env: 
    - name: USER_1
      valueFrom:
        secretKeyRef:
          name: credentials
          key: USERNAME_1
    - name: PWD_1
      valueFrom:
        secretKeyRef:
          name: credentials
          key: PASSWORD_1
    - name: USER_2
      valueFrom:
        secretKeyRef:
          name: credentials
          key: USERNAME_2
    - name: PWD_2
      valueFrom:
        secretKeyRef:
          name: credentials
          key: PASSWORD_2
